# Generated by Django 3.2.3 on 2021-06-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_userlikecomment_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlikecomment',
            table='user_like_comment',
        ),
    ]
