# Generated by Django 3.2.3 on 2021-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='act_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
