# Generated by Django 3.2.3 on 2021-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_userinfo_act_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='act_point',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
