# Generated by Django 3.2 on 2021-04-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
    ]
