# Generated by Django 3.2.3 on 2021-06-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_userinfo_act_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
