# Generated by Django 3.2 on 2021-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=255)),
                ('cover_path', models.CharField(blank=True, max_length=255, null=True)),
                ('rls_yn', models.CharField(max_length=10)),
                ('like_cnt', models.IntegerField(blank=True, null=True)),
                ('wrt_dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('page_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('wrt_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('mdfcn_dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'pages',
                'managed': False,
            },
        ),
    ]
