# Generated by Django 3.2.3 on 2021-06-04 13:47

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=255)),
                ('author_id', models.CharField(max_length=150)),
                ('cover_path', models.CharField(blank=True, max_length=255, null=True)),
                ('rls_yn', models.CharField(max_length=10)),
                ('like_cnt', models.IntegerField(blank=True, null=True)),
                ('wrt_dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('page_title', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('description', martor.models.MartorField()),
                ('wrt_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('mdfcn_dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'pages',
                'managed': False,
            },
        ),
    ]
