# Generated by Django 3.2.3 on 2021-07-07 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('author_id', models.CharField(max_length=150)),
                ('cover_path', models.CharField(blank=True, max_length=255, null=True)),
                ('rls_yn', models.CharField(max_length=10)),
                ('like_cnt', models.IntegerField(blank=True, null=True)),
                ('wrt_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('enfc_dt', models.DateTimeField(blank=True, null=True)),
                ('codes_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('mdfcn_dt', models.DateTimeField(auto_now=True)),
                ('hit_count', models.IntegerField(blank=True, default=0, null=True)),
                ('code_gubun', models.CharField(choices=[('0', '법령'), ('1', '행정규칙'), ('2', '자치법규')], max_length=2)),
                ('wiki_gubun', models.CharField(blank=True, choices=[('0', '전체'), ('1', '설계'), ('2', '재료'), ('3', '시공'), ('4', '설비'), ('5', '환경'), ('6', '도시'), ('7', '기타')], default=7, max_length=10, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('page_title', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField(blank=True, default=0, null=True)),
                ('depth', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('wrt_dt', models.DateTimeField(auto_now_add=True)),
                ('mdfcn_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLikeBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_like_book',
                'managed': False,
            },
        ),
    ]
