# Generated by Django 3.2.3 on 2021-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikeBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_like_book',
                'managed': False,
            },
        ),
    ]
