# Generated by Django 3.2.3 on 2021-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'bookmark',
                'managed': False,
            },
        ),
    ]
